CREATE TABLE [dbo].[CompatibilitiesList]
(
	[ID] INT NOT NULL PRIMARY KEY, 
    [Part] NCHAR(10) NULL, 
    [SellerID] NCHAR(10) NULL, 
    [Make] NCHAR(10) NULL, 
    [Model] NCHAR(10) NULL, 
    [Year] NCHAR(10) NULL, 
    [PartType] NCHAR(10) NULL, 
    [comments] NCHAR(10) NULL, 
    [cylinders?] NCHAR(10) NULL, 
    [1] NCHAR(10) NULL, 
    [2] NCHAR(10) NULL, 
    [Aspiration] NCHAR(10) NULL, 
    [4] NCHAR(10) NULL, 
    [5] NCHAR(10) NULL, 
    [Block] NCHAR(10) NULL, 
    [Bodynumdoors] NCHAR(10) NULL, 
    [bodytype] NCHAR(10) NULL, 
    [6] NCHAR(10) NULL, 
    [7] NCHAR(10) NULL, 
    [cc] NCHAR(10) NULL, 
    [cid] NCHAR(10) NULL, 
    [cylinderheadtype] NCHAR(10) NULL, 
    [cylinders] NCHAR(10) NULL, 
    [8] NCHAR(10) NULL, 
    [enginedesignation] NCHAR(10) NULL, 
    [9] NCHAR(10) NULL, 
    [10] NCHAR(10) NULL, 
    [enginevin] NCHAR(10) NULL
)
