CREATE TABLE [dbo].[GTINs]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
    [CompanyPrefix] NVARCHAR(255) NULL, 
    [GTIN] NVARCHAR(255) NULL, 
    [SKU] NVARCHAR(255) NULL, 
    [User] NVARCHAR(255) NULL, 
    [DateReserved] DATETIME2(0) NULL
)
